"""empty message

Revision ID: 4f8b65bd5b0d
Revises: 
Create Date: 2018-08-07 16:00:18.707925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8b65bd5b0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=360), nullable=True),
    sa.Column('link', sa.String(length=360), nullable=True),
    sa.Column('rating', sa.Float(precision=2), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.Column('reg_low_price', sa.Float(precision=2), nullable=True),
    sa.Column('reg_high_price', sa.Float(precision=2), nullable=True),
    sa.Column('dis_low_price', sa.Float(precision=2), nullable=True),
    sa.Column('dis_high_price', sa.Float(precision=2), nullable=True),
    sa.Column('img_link', sa.String(length=360), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_img_link'), 'product', ['img_link'], unique=True)
    op.create_index(op.f('ix_product_link'), 'product', ['link'], unique=True)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_link'), table_name='product')
    op.drop_index(op.f('ix_product_img_link'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
