"""empty message

Revision ID: f9d261bbc8a8
Revises: 4f8b65bd5b0d
Create Date: 2018-08-07 17:10:17.073439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d261bbc8a8'
down_revision = '4f8b65bd5b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_img_link', table_name='product')
    op.create_index(op.f('ix_product_img_link'), 'product', ['img_link'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_img_link'), table_name='product')
    op.create_index('ix_product_img_link', 'product', ['img_link'], unique=1)
    # ### end Alembic commands ###
